spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms_sys
    username: root
    password: Heqinglin2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath:bms/mapper/*.xml
    type-aliases-package: bms.domain
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: alexanderbruce044@gmail.com
    password: ngwmvmwylbqavmzr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  key: VHJ1c3R3b3JrT3BhZHVzJTIwU2VjdXJlU2VjcmV0Q29tcGxleEJ0b2xkY29tcGxleENvbmZpZyUyMExhcmdlU2VjcmV0S2V5

mode: PROD

logging:
  file:
    name: log/log.log
  level:
    root: INFO
    bms.exception: ERROR
