spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms_sys
    username: root
    password: Heqinglin2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath:bms/mapper/*.xml
    type-aliases-package: bms.domain
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: log/log.log
  level:
    root: info